import type { MenuItem } from "../components/MenuCard/types";

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Truffle Mushroom Risotto",
    description:
      "Creamy Arborio rice with wild mushrooms, truffle oil, and aged Parmesan cheese",
    price: 450,
    image:
      "https://images.pexels.com/photos/1721932/pexels-photo-1721932.jpeg?cs=srgb&dl=baking-bride-cake-1721932.jpg&fm=jpg",
    topView: "/top.png",
    frontView: "/side.png",
    angleView: "/side.png",
    category: "main-course",
    isVeg: true,
    isSpicy: false,
    rating: 4.8,
    prepTime: "25 min",
    addOns: [
      { id: "a1", name: "Extra Truffle Oil", price: 80 },
      { id: "a2", name: "Grilled Vegetables", price: 60 },
      { id: "a3", name: "Extra Parmesan", price: 40 },
    ],
    has3DModel: true,
  },
  {
    id: "2",
    name: "Margherita Pizza",
    description:
      "Classic Italian pizza with San Marzano tomatoes, fresh mozzarella, and basil",
    price: 380,
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=800",
    category: "pizza",
    isVeg: true,
    isSpicy: false,
    rating: 4.6,
    prepTime: "20 min",
    addOns: [
      { id: "a4", name: "Extra Cheese", price: 50 },
      { id: "a5", name: "Jalapenos", price: 30 },
      { id: "a6", name: "Olives", price: 35 },
    ],
    has3DModel: true,
  },
  {
    id: "3",
    name: "Gourmet Burger",
    description:
      "Angus beef patty with caramelized onions, aged cheddar, and secret sauce",
    price: 320,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    category: "burgers",
    isVeg: false,
    isSpicy: false,
    rating: 4.7,
    prepTime: "18 min",
    addOns: [
      { id: "a7", name: "Extra Patty", price: 120 },
      { id: "a8", name: "Bacon", price: 60 },
      { id: "a9", name: "Avocado", price: 50 },
    ],
    has3DModel: true,
  },
  {
    id: "4",
    name: "Caesar Salad",
    description:
      "Crisp romaine lettuce with classic Caesar dressing, croutons, and shaved Parmesan",
    price: 220,
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800",
    category: "starters",
    isVeg: true,
    isSpicy: false,
    rating: 4.4,
    prepTime: "10 min",
    addOns: [
      { id: "a10", name: "Grilled Chicken", price: 80 },
      { id: "a11", name: "Shrimp", price: 120 },
      { id: "a12", name: "Extra Dressing", price: 25 },
    ],
    has3DModel: false,
  },
  {
    id: "5",
    name: "Butter Chicken",
    description:
      "Tender chicken in rich tomato-butter gravy with aromatic spices",
    price: 380,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800",
    category: "main-course",
    isVeg: false,
    isSpicy: true,
    rating: 4.9,
    prepTime: "30 min",
    addOns: [
      { id: "a13", name: "Extra Gravy", price: 40 },
      { id: "a14", name: "Naan Bread", price: 45 },
      { id: "a15", name: "Basmati Rice", price: 50 },
    ],
    has3DModel: true,
  },
  {
    id: "6",
    name: "Tiramisu",
    description:
      "Classic Italian dessert with espresso-soaked ladyfingers and mascarpone cream",
    price: 280,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
    category: "desserts",
    isVeg: true,
    isSpicy: false,
    rating: 4.8,
    prepTime: "5 min",
    addOns: [
      { id: "a16", name: "Extra Cocoa", price: 15 },
      { id: "a17", name: "Espresso Shot", price: 40 },
    ],
    has3DModel: true,
  },
  {
    id: "7",
    name: "Paneer Tikka",
    description:
      "Smoky grilled cottage cheese with bell peppers and Indian spices",
    price: 280,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800",
    category: "starters",
    isVeg: true,
    isSpicy: true,
    rating: 4.5,
    prepTime: "15 min",
    addOns: [
      { id: "a18", name: "Mint Chutney", price: 20 },
      { id: "a19", name: "Extra Paneer", price: 80 },
    ],
    has3DModel: true,
  },
  {
    id: "8",
    name: "Pepperoni Pizza",
    description:
      "Loaded with spicy pepperoni, mozzarella cheese on a crispy thin crust",
    price: 420,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800",
    category: "pizza",
    isVeg: false,
    isSpicy: true,
    rating: 4.7,
    prepTime: "22 min",
    addOns: [
      { id: "a20", name: "Extra Pepperoni", price: 70 },
      { id: "a21", name: "Stuffed Crust", price: 60 },
    ],
    has3DModel: true,
  },
  {
    id: "9",
    name: "Chocolate Lava Cake",
    description:
      "Warm chocolate cake with a molten center, served with vanilla ice cream",
    price: 320,
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800",
    category: "desserts",
    isVeg: true,
    isSpicy: false,
    rating: 4.9,
    prepTime: "12 min",
    addOns: [
      { id: "a22", name: "Extra Ice Cream", price: 50 },
      { id: "a23", name: "Chocolate Sauce", price: 30 },
    ],
    has3DModel: true,
  },
  {
    id: "10",
    name: "Mango Smoothie",
    description:
      "Fresh Alphonso mango blended with yogurt and a hint of cardamom",
    price: 180,
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299ber?w=800",
    category: "beverages",
    isVeg: true,
    isSpicy: false,
    rating: 4.6,
    prepTime: "5 min",
    addOns: [
      { id: "a24", name: "Protein Powder", price: 40 },
      { id: "a25", name: "Extra Mango", price: 30 },
    ],
    has3DModel: false,
  },
  {
    id: "11",
    name: "Veggie Burger",
    description:
      "Crispy vegetable patty with fresh lettuce, tomato, and chipotle mayo",
    price: 260,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800",
    category: "burgers",
    isVeg: true,
    isSpicy: false,
    rating: 4.3,
    prepTime: "15 min",
    addOns: [
      { id: "a26", name: "Extra Patty", price: 80 },
      { id: "a27", name: "Cheese Slice", price: 30 },
    ],
    has3DModel: true,
  },
  {
    id: "12",
    name: "Iced Coffee",
    description:
      "Cold brew coffee with milk and a touch of vanilla, served over ice",
    price: 150,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800",
    category: "beverages",
    isVeg: true,
    isSpicy: false,
    rating: 4.5,
    prepTime: "3 min",
    addOns: [
      { id: "a28", name: "Extra Shot", price: 40 },
      { id: "a29", name: "Caramel Syrup", price: 25 },
    ],
    has3DModel: false,
  },
];

